blank_issues_enabled: false
contact_links:
  - name: Qbox Discord Server
    url: https://discord.gg/Z6Whda5hHA
    about: Ask questions, receive support, and discuss with the community in our Discord server.
